services:
    sio_test:
        user: app
        build:
            context: .
            args:
                USER_ID: ${USER_ID}
        depends_on:
            - sio_test_db
        ports:
            - "8337:8337"
        volumes:
            - .:/app:rw
        environment:
            - APP_ENV=dev

    sio_test_db:
        image: postgres
        container_name: sio_test_db
        volumes:
            - ./postgresql/data:/var/lib/postgresql/data
        ports:
            - "5433:5432"
        environment:
            POSTGRES_DB: sio_test
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
